# Generated by Django 5.2.1 on 2025-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="num_of_servings",
            field=models.PositiveIntegerField(),
        ),
    ]
