# Generated by Django 5.2.1 on 2025-05-18 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_alter_recipe_cook_time_alter_recipe_num_of_servings"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="num_of_servings",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
