
services:
  api:
    build: .
    env_file: .env
    command: python /recipe-api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/recipe-api
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: